= AsciiBook

:link-docker-image: https://hub.docker.com/r/asciidoctor/docker-asciidoctor
:link-asciidoctor-pdf: https://asciidoctor.org/docs/asciidoctor-pdf/
:link-asciidoctor-vscode-ext: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode

This is a template repository for a lightweight toolchain for authoring technical books from AsciiDoc source.

== Features

* Use AsciiDoc for authoring books.
* No local installation required – build tools run in Docker.
* Generate books in PDF, EPUB, and HTML formats.
* Offer your customers an alternative dark-themed PDF.

== Documentation

=== Requirements

The only requirements are *Docker Desktop* and a good AsciiDoc editor – try VS Code with the {link-asciidoctor-vscode-ext}[AsciiDoctor extension].

On Windows, it is RECOMMENDED to configure Docker to use WSL 2, and then run the build commands from WSL in a terminal. Linux emulators like Git Bash are insufficient.

The script to start the container will run the container under the current user and group. You should add your user to the `docker` group, which will allow you to run Docker commands without needing to use `sudo`.

----
$ sudo usermod -aG docker [your-username]
----

Also, make sure the `run/*` scripts are executable:

----
$ chmod +x run/*
----

=== Building

The {link-docker-image}[official Asciidoctor Docker container image] is used to compile books from the AsciiDoc source files.

To start the Docker container, run:

----
$ ./run/start
----

The start script keeps the container running indefinitely (until it is explicitly stopped), so you can re-run the build command again and again, and each time it will be executed immediately without restarting the container.

To compile your book, run the `build` script:

----
$ ./run/build
----

TIP: If you get a permissions error on the `dist` directory, delete it. The `build` script will recreate the directory with the correct permissions.

The script will build the book in PDF, EPUB, and HTML formats, and place the output files in the `dist` directory. Both light-mode and dark-mode versions of the PDF will be generated.

When you've finished your work, stop the container:

----
$ ./run/stop
----

=== Advanced usage

If you want to run custom AsciiDoctor commands, you can run the container in interactive mode. The following command maps this repository's root directory to the `/documents` directory inside the container, and takes you to the container's shell environment.

[source,bash]
----
docker run -it -v ./:/documents/ asciidoctor/docker-asciidoctor:1.88
----

From the container's shell environment, run the following command to use the {link-asciidoctor-pdf}[`asciidoctor-pdf`] program to compile the book to PDF format:

[source,bash]
----
asciidoctor-pdf -D dist -o "book.pdf" src/index.adoc
----

See the https://github.com/asciidoctor/docker-asciidoctor[Asciidoctor Docker Container documentation] for further documentation.

Type `Ctrl`+`D` to exit the container shell.

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[MIT license]

Acknowledgement: This project started as a partial fork of https://github.com/lirantal/asciidoc-book-starter/[Liran Tal's AsciiDoc Book Starter].
