= AsciiBook

:link-docker-image: https://hub.docker.com/r/asciidoctor/docker-asciidoctor
:link-asciidoctor-pdf: https://asciidoctor.org/docs/asciidoctor-pdf/
:link-asciidoctor-vscode-ext: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode

This is a template repository for a lightweight toolchain for authoring technical books from AsciiDoc source.

== Features

* Use AsciiDoc for authoring books.
* Supports formatting commonly used in technical books, such as code blocks.
* Use the official Asciidoctor Docker image to compile books.
* No local installation required – just Docker.
* Generate books in PDF, EPUB, and HTML formats.
* Two PDFs generated: one optimized for physical bookbinding, one optimized for screen reading.
* Plus, offer your customers an alternative dark-themed PDF for screen reading.
* Automatic table-of-contents generation.
* Chapters organized in a directory structure.
* Easy theme customization. Lots of bundled fonts to choose from.
* Includes a basic GitHub Actions workflow to build the book in PDF format.

== Documentation

=== Requirements

The only requirements are *Docker Desktop* and a good AsciiDoc editor – try VS Code with the {link-asciidoctor-vscode-ext}[AsciiDoctor extension].

On Windows, it is RECOMMENDED to configure Docker to use WSL 2, and then run the build commands from a WSL terminal. Linux emulators like Git Bash are not always sufficient.

The script to start the container will run the container under the current user and group. You should add your user to the `docker` group, which will allow you to run Docker commands without needing to use `sudo`.

----
$ sudo usermod -aG docker [your-username]
----

Also, make sure the `run/*` scripts are executable:

----
$ chmod +x run/*
----

=== Editing

The source files for the book – AsciiDoc files, plus images, style sheets, and other assets – are all bundled together in the `src` directory.

The contents of the `src` directory are organized to model the structure of the book.

----
.
├── README.md
└── src
    └── _/
    │   ├── fonts/
    │   ├── images/
    │   └── themes/
    │
    ├── index.adoc
    ├── preface.adoc
    ├── foreword.adoc
    │
    ├── chapter-01
    │   └── index.adoc
    ├── chapter-02
    │   └── index.adoc
    └── chapter-03
        └── index.adoc
----

The main entry file for the book is `src/index.adoc`. This is the file that the `asciidoctor` program targets when compiling the book. All other `*.adoc` files are included in the book by referencing them from the root `index.adoc` file.

The `src/_` directory is the "includes" directory that contains all the assets – fonts, images, and themes – that are referenced from the `*.adoc` files.

Document attributes are defined at the top of the `src/index.adoc` file. Some of the options that can be modified inlude:

* The `pygments-style` option sets the style for source code highlighting. Options include:
  ** `friendly`
  ** `colorful`
  ** `fruity` (dark background)
  ** `monokai` (dark background)
  ** `stata-dark` (dark background)
  ** `stata-light`
  ** `tango`
  ** `zenburn` (dark background)
  ** `vs`

=== Building

The {link-docker-image}[official Asciidoctor Docker container image] is used to compile books from the AsciiDoc source files.

To start the Docker container, run:

----
$ ./run/start
----

The start script keeps the container running indefinitely (until it is explicitly stopped), so you can re-run the build command again and again, and each time it will be executed immediately without restarting the container.

To compile your book, run the `build` script:

----
$ ./run/build
----

TIP: If you get a permissions error on the `dist` directory, delete it then re-run the `build` script. The `build` script should recreate the directory with the correct permissions.

The script will build the book in PDF, EPUB, and HTML formats, and place the output files in the `dist` directory. Both light-mode and dark-mode versions of the PDF will be generated.

When you've finished your work, stop the container:

----
$ ./run/stop
----

=== Advanced usage

If you want to run custom AsciiDoctor commands, you can run the container in interactive mode. The following command maps this repository's root directory to the `/documents` directory inside the container, and takes you to the container's shell environment.

[source,bash]
----
docker run -it -v ./:/documents/ asciidoctor/docker-asciidoctor:1.88
----

From the container's shell environment, run the following command to use the {link-asciidoctor-pdf}[`asciidoctor-pdf`] program to compile the book to PDF format:

[source,bash]
----
asciidoctor-pdf -D dist -o "book.pdf" src/index.adoc
----

See the https://github.com/asciidoctor/docker-asciidoctor[Asciidoctor Docker Container documentation] for further documentation.

Type `Ctrl`+`D` to exit the container shell.

=== CI/CD build

There's a simple https://github.com/kieranpotts/asciibook/actions/workflows/generate-pdf.yaml[GitHub Actions workflow] that builds the book in the PDF format with the default (light) theme, and uploads the resulting PDF file as an artifact (which is retained for 5 days). The workflow is triggered manually.

You can use this workflow as a starting point for your own automated build pipeline.

== Acknowledgements

This project started as a partial fork of https://github.com/lirantal/asciidoc-book-starter/[Liran Tal's AsciiDoc Book Starter]. Other sources of inspiration include https://github.com/akosma/eBook-Template/[Adrian Kosmaczewski's eBook Template].

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[MIT license]
