#!/usr/bin/env sh

mkdir -p dist
rm -rf dist/*

# The container name.
NAME=asciidoctor

# The directory where the book source is located,
# relative to the project root.
SRC_DIR=./src

# The directory where the book's generated output files will be created,
# relative to the project root.
DIST_DIR=./dist

# Run `asciidoctor-pdf` inside the `asciidoctor` container, in interactive
# mode. See https://github.com/asciidoctor/docker-asciidoctor for options.
#
docker exec -it "$NAME" asciidoctor-pdf \
    -D $DIST_DIR \
    -o "book.pdf" \
    $SRC_DIR/index.adoc

docker exec -it "$NAME" asciidoctor-pdf \
    -D $DIST_DIR \
    -o "book-dark.pdf" \
    -a pdf-theme=dark \
    $SRC_DIR/index.adoc

docker exec -it "$NAME" asciidoctor-epub3 \
    -D $DIST_DIR \
    -o "book.epub" \
    $SRC_DIR/index.adoc
